name: moon_phase_plus
description: Flutter plugin that creates moon widgets according to the moon's phase. 
version: 0.0.2+1
homepage: https://github.com/helal-muneer/moon_phase_plus

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.novaGeni.moon_phase_plus
        pluginClass: MoonPhasePlusPlugin
      ios:
        pluginClass: MoonPhasePlusPlugin
      web:
        pluginClass: MoonPhasePlusWeb
        fileName: moon_phase_plus_web.dart
